export enum EmailValidationStatus {
  PENDING = 'PENDING',
  VALID = 'VALID',
  INVALID_FORMAT = 'INVALID_FORMAT',
  NO_MX_RECORDS = 'INVALID',
  UNDELIVERABLE_ADDRESS = 'UNDELIVERABLE_ADDRESS',
  DISPOSABLE_ADDRESS = 'DISPOSABLE_ADDRESS',
}
